name: Docker build
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/build.yml
      - .dockerignore
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build .
